### PR TITLE
[TEST-1525] Enforce uniqueness in node_fingerprint

### PR DESCRIPTION
**Pull request by carsongee**
# Changes
Add UNIQUENESS constraint and handle duplicate INSERTS into the node_fingerprint link table by ignore duplicate inserts.

## Testing
Verified with https://ci-test.devinfra.drdev.io/job/DataRobot_Testmon_Update_v1/93/ and DataRobot changes: 
https://github.com/datarobot/DataRobot/pull/67435

### CODE REVIEW

**Comment by carsongee** [comment]
jarvis test this

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**0.06** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Review by DKorytkin — APPROVED** [review]
Nice 👍 
And now we can running not all tests for the update, am I right? 🎉

**Comment by carsongee** [comment]
> Nice 👍
> And now we can running not all tests for the update, am I right? 🎉

I certainly hope so....there might be a performance problem that makes it slower than fresh due to indices, but I won't really know until we get it running that way. I'll get it running periodically on ci-test after this gets through the build pipelines

**Comment by datarobot-jarvis** [comment]
:dollar: Total cost of executing tests in Jenkins: $**1.34** USD.

[What is this all about?](http://bit.ly/2BahK4V)

**Pull request merged**
